### ISSUE TITLE
Export Site Error

### ISSUE THREAD

**Issue by joserh-git** [imperva/incapsula-cli#14]
Hello,

When using the export site CLI (https://github.com/imperva/incapsula-cli), it errors out with the following (output has been sanitized):

[REDACTED]@[REDACTED]-174915:~/.incap$ incap site export --site_id="[REDACTED]"
-------------------------------------------------------------------------------------------------
Site ID: [REDACTED]
Domain: [REDACTED].com
Display Name = [REDACTED].com
Account ID: [REDACTED]
Site status: fully-configured
Site Creation Date: 2021-05-13 15:37:28
Active Status = active
Extended DDoS = 1000000
Seal Location = No seal
Acceleration Level: off
Log Level = full
-------------------------------------------------------------------------------------------------
Current DNS information is set to the following:
-------------------------------------------------------------------------------------------------
The current CNAME Record for joserh.mscloudwaf.com is otju6pk.impervadns.net
-------------------------------------------------------------------------------------------------
Original DNS information was set to the following:
-------------------------------------------------------------------------------------------------
The original CNAME Record for [REDACTED].com was [REDACTED].amazonaws.com
-------------------------------------------------------------------------------------------------
No additional Errors
-------------------------------------------------------------------------------------------------
Origin Server IP/CNAME: [REDACTED].
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
No ACLs
-------------------------------------------------------------------------------------------------
Security settings are as follows:
-------------------------------------------------------------------------------------------------
SQL Injection is set to Block Request.
Cross Site Scripting is set to Block Request.
Illegal Resource Access is set to Block Request.
Bot Access Control setting are: Block Bad Bots=True and Challenge Suspected Bots=False.
DDoS setting are: DDoS Activation Mode=Auto and DDoS Traffic Threshold=1000.
Backdoor Protect is set to Auto-Quarantine.
Remote File Inclusion is set to Block Request.
IncapRules is set to Ignore.
API Specification Violation is set to Block Request.
Account Takeover is set to Ignore.
Advanced Bot Protection is set to Ignore.

SSL info following:
Custom certificate used: False

SSL on origin server detected: True, detected status: ok.

Warnings for the following:
Traceback (most recent call last):
  File "/home/jose/.local/bin/incap", line 8, in <module>
    sys.exit(main())
  File "/home/jose/.local/lib/python3.8/site-packages/cwafcli/__main__.py", line 9, in main
    sys.exit(clidriver.main(sys.argv[1:]))
  File "/home/jose/.local/lib/python3.8/site-packages/cwafcli/Utils/clidriver.py", line 40, in main
    response = args.func(args)
  File "/home/jose/.local/lib/python3.8/site-packages/cwafcli/Utils/export.py", line 51, in export
    if int(result.get('res')) != 0:
AttributeError: 'NoneType' object has no attribute 'get'

The above behavior is occurring for multiple users. We are running the following pip and python versions:

User1:
Python 3.10.5
pip 22.1.2

User2:
Python 3.6.8
pip 9.0.3

Me:
Python 3.10.6
Pip 22.2.1

Please let me know if you need additional information. Thank you.

**Comment by joeymoore** [comment]
Hello @joserh-git can you please email me at joe.mooore@imperva.com to discuss this?

**Comment by joserh-git** [comment]
Hello Joe, reaching out to you directly. Thank you.
