### ISSUE TITLE
Site export call fails if there is a WafOverride Incap Rule and no other incap rules on the site

### ISSUE THREAD

**Issue by AaronSeibert** [imperva/incapsula-cli#20]
This may have impact elsewhere, so far it's only been discovered on site exports. When the WafOverride rule actions were added, its representation in the API response for the incapRules/list endpoint was added at the same level as the 'All' key for security rules:

```
{
  "rate_rules": {},
  "res": "0",
  "delivery_rules": {},
  "custom_error_response_rules": {},
  "incap_rules": {
    "WafOverride": [
      {
        "filter": "URL contains \"^/\"",
        "name": "test override",
        "action": "RULE_ACTION_WAF_OVERRIDE",
        "id": "3153841",
        "enabled": "true"
      }
    ]
  }
}
``` 

This is causing a logic flaw when parsing incaprules for a given site, as we're just checking for the existence of an incap_rules key in the returned object and if it exists, pulling the values of the 'All' key. Unfortunately, with WafOverride there is no 'All' key.

Stacktrace:

```
Traceback (most recent call last):
  File "/opt/homebrew/bin/incap", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/cwafcli/__main__.py", line 9, in main
    sys.exit(clidriver.main(sys.argv[1:]))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/cwafcli/Utils/clidriver.py", line 46, in main
    response = args.func(args)
               ^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/cwafcli/Utils/export.py", line 65, in export
    export_site(result, path, filename, args)
  File "/opt/homebrew/lib/python3.11/site-packages/cwafcli/Utils/export.py", line 82, in export_site
    _filename = path + '/' + create_filename(filename, site) + '.json'
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/cwafcli/Utils/export.py", line 94, in create_filename
    site = Site(site)
           ^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/cwafcli/Sites/site.py", line 43, in __init__
    self.incap_rules = self.policies['incap_rules']['All']
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
KeyError: 'All'
```

**Comment by AaronSeibert** [comment]
Workaround: Create a disabled security rule
